name: Coding Standards

on:
    push:
      branches:
        - '*'
    pull_request:
      branches:
        - '*'

env:
  COMPOSER_PROCESS_TIMEOUT: 0
  COMPOSER_NO_INTERACTION: 1
  COMPOSER_NO_AUDIT: 1

jobs:
  phplint:
      permissions:
          contents: write
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - name: "laravel-pint"
            uses: aglipanci/laravel-pint-action@latest
            with:
                configPath: './pint.json'

          - name: Commit changes
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
                commit_message: PHP Linting (Pint)
                skip_fetch: true

