name: run-tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1
      XDEBUG_MODE: coverage
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.1, 8.2, 8.3, 8.4 ]
        laravel: [ 10.*, 11.*, 12.* ]
        exclude:
          - php: 8.1
            laravel: 11.*
          - php: 8.1
            laravel: 12.*
        include:
          - laravel: 12.*
            testbench: 10.*
          - laravel: 11.*
            testbench: 9.*
          - laravel: 10.*
            testbench: 8.*

    name: PHP${{ matrix.php }} - Laravel${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: xdebug

      - name: Install latest OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl libssl-dev

      - name: Install dependencies
        run: |
          composer require "illuminate/support:${{ matrix.laravel }}" "illuminate/validation:${{ matrix.laravel }}" --no-update
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-update
          composer update --prefer-dist --no-suggest

      - name: Execute tests
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.clover




